universe     = vanilla
initialdir   = /home/pbrem/PTA-Fp/Steve
executable   = /home/pbrem/PTA-Fp/Steve/wrapper_upper_notvaryC.sh
arguments    = $(Process)
environment  = OUTDIR=.;TEMPO2=/home/pbrem/tempo;LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/pbrem/cula/lib64:/home/pbrem/tempo/lib
output       = $(Process).out
error        = $(Process).err
log          = $(Process).log
request_cpus = 1
notification = Never

queue 250
