universe     = vanilla
executable   = /home/pbrem/PTA-Fp/Steve/wrapper_upper_varyC.sh
initialdir   = /home/pbrem/PTA-Fp/Steve
arguments    = $(Process)
environment  = OUTDIR=.;TEMPO2=/home/pbrem/tempo;LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/pbrem/cula/lib64:/home/pbrem/tempo/lib
output       = $(Process).out
error        = $(Process).err
log          = $(Process).log
request_cpus = 1
request_memory = 5000
notification = Never

queue 5
